import Head from 'next/head'
import Image from 'next/image'
import {HomePage} from './Component/HomePage'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Magnet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage/>
    </div>
  )
}
